#include "html.h"

/* ---------- Páginas HTML do Sistema PicoAtmos ---------- */
// Este arquivo contém todas as páginas web do sistema de monitoramento atmosférico
// Cada página é definida como uma string constante contendo HTML, CSS e JavaScript

/* ---- Página HTML Principal ------------------------------------ */
// Página inicial com dashboard dos sensores e navegação principal
// Atualiza automaticamente os valores dos sensores a cada 2 segundos
const char HTML_BODY[] =

    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>PicoAtmos - Monitor Atmosférico</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { font-family: sans-serif; text-align: center; padding: 20px; margin: 0; background: #f0f8ff; }"
    ".container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
    "h1 { color: #2c3e50; margin-top: 0; }"
    ".nav-buttons { margin: 20px 0; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }"
    ".nav-btn { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; text-decoration: none; }"
    ".nav-btn:hover { background: #2980b9; }"
    ".calibration-btn { background: #e67e22; }"
    ".calibration-btn:hover { background: #d35400; }"
    ".graficos-btn { background: #9b59b6; }"
    ".graficos-btn:hover { background: #8e44ad; }"
    ".estados-btn { background: #e74c3c; }"
    ".estados-btn:hover { background: #c0392b; }"
    ".limites-btn { background: #27ae60; }"
    ".limites-btn:hover { background: #229954; }"
    ".sensor-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 15px; margin: 20px 0; }"
    ".sensor-card { background: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 4px solid #3498db; }"
    ".sensor-value { font-size: 24px; font-weight: bold; color: #2c3e50; }"
    ".sensor-unit { font-size: 14px; color: #7f8c8d; }"
    ".status-info { background: #ecf0f1; padding: 10px; border-radius: 4px; margin-top: 15px; }"
    "</style>"
    "<script>"
    "function atualizarDados() {"
    "fetch('/dados').then(res => res.json()).then(data => {"
    "document.getElementById('temp_aht').innerText = data.temp_aht.toFixed(1);"
    "document.getElementById('temp_bmp').innerText = data.temp_bmp.toFixed(1);"
    "document.getElementById('temp_atual').innerText = data.temp_media.toFixed(1);"
    "document.getElementById('umid_atual').innerText = data.umidade.toFixed(1);"
    "document.getElementById('press_atual').innerText = data.pressao.toFixed(1);"
    "});"
    "}"
    "window.onload = function() { atualizarDados(); setInterval(atualizarDados, 2000); };"
    "</script></head><body>"
    "<div class='container'>"
    "<h1>🌡️ PicoAtmos - Monitor Atmosférico</h1>"
    "<div class='nav-buttons'>"
    "<a href='/' class='nav-btn'>🏠 Principal</a>"
    "<a href='/graficos' class='nav-btn graficos-btn'>📊 Gráficos</a>"
    "<a href='/estados' class='nav-btn estados-btn'>🚨 Estados</a>"
    "<a href='/limites' class='nav-btn limites-btn'>⚙️ Limites</a>"
    "<a href='/calibracao' class='nav-btn calibration-btn'>🔧 Calibração</a>"
    "</div>"
    "<div class='sensor-grid'>"
    "<div class='sensor-card'><div>Temperatura AHT</div><div class='sensor-value'><span id='temp_aht'>--</span><span class='sensor-unit'>°C</span></div></div>"
    "<div class='sensor-card'><div>Temperatura BMP</div><div class='sensor-value'><span id='temp_bmp'>--</span><span class='sensor-unit'>°C</span></div></div>"
    "<div class='sensor-card'><div>Temperatura Média</div><div class='sensor-value'><span id='temp_atual'>--</span><span class='sensor-unit'>°C</span></div></div>"
    "<div class='sensor-card'><div>Umidade</div><div class='sensor-value'><span id='umid_atual'>--</span><span class='sensor-unit'>%</span></div></div>"
    "<div class='sensor-card'><div>Pressão</div><div class='sensor-value'><span id='press_atual'>--</span><span class='sensor-unit'>hPa</span></div></div>"
    "</div>"
    "<div class='status-info'><div>Sistema PicoAtmos ativo</div><div>Atualizando a cada 2 segundos</div><div>Acesse as seções específicas através dos botões acima</div></div>"
    "</div></body></html>";

/* ---- Página de Gráficos --------------------------------------- */
const char HTML_GRAFICOS[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Gráficos - PicoAtmos</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<script src='https://cdn.jsdelivr.net/npm/chart.js'></script>"
    "<style>"
    "body { font-family: sans-serif; text-align: center; padding: 20px; margin: 0; background: #f0f8ff; }"
    ".container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
    "h1 { color: #2c3e50; margin-top: 0; }"
    ".nav-buttons { margin: 20px 0; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }"
    ".nav-btn { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; text-decoration: none; }"
    ".nav-btn:hover { background: #2980b9; }"
    ".charts-container { margin: 30px 0; }"
    ".charts-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; }"
    ".chart-card { background: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #ddd; }"
    ".chart-title { font-weight: bold; margin-bottom: 15px; color: #2c3e50; text-align: center; }"
    "canvas { max-width: 100%; height: 300px !important; }"
    "</style>"
    "<script>"
    "let charts = {};"
    "let chartData = { tempMedia: [], umidade: [], pressao: [], labels: [] };"
    "function criarGraficos() {"
    "const ctx1 = document.getElementById('chartTempMedia').getContext('2d');"
    "const ctx2 = document.getElementById('chartUmidade').getContext('2d');"
    "const ctx3 = document.getElementById('chartPressao').getContext('2d');"
    "charts.tempMedia = new Chart(ctx1, {"
    "type: 'line', data: { labels: chartData.labels, datasets: [{"
    "label: 'Temperatura Média (°C)', data: chartData.tempMedia,"
    "borderColor: '#e74c3c', backgroundColor: 'rgba(231, 76, 60, 0.1)', tension: 0.4"
    "}]}, options: { responsive: true, maintainAspectRatio: false, scales: { y: { beginAtZero: false }}}"
    "});"
    "charts.umidade = new Chart(ctx2, {"
    "type: 'line', data: { labels: chartData.labels, datasets: [{"
    "label: 'Umidade (%)', data: chartData.umidade,"
    "borderColor: '#3498db', backgroundColor: 'rgba(52, 152, 219, 0.1)', tension: 0.4"
    "}]}, options: { responsive: true, mantainAspectRatio: false, scales: { y: { beginAtZero: true, max: 100 }}}"
    "});"
    "charts.pressao = new Chart(ctx3, {"
    "type: 'line', data: { labels: chartData.labels, datasets: [{"
    "label: 'Pressão (hPa)', data: chartData.pressao,"
    "borderColor: '#27ae60', backgroundColor: 'rgba(39, 174, 96, 0.1)', tension: 0.4"
    "}]}, options: { responsive: true, maintainAspectRatio: false, scales: { y: { beginAtZero: false }}}"
    "});"
    "}"
    "function atualizarGraficos(data) {"
    "const agora = new Date();"
    "const tempo = agora.toLocaleTimeString();"
    "chartData.tempMedia.push(data.temp_media);"
    "chartData.umidade.push(data.umidade);"
    "chartData.pressao.push(data.pressao);"
    "chartData.labels.push(tempo);"
    "const maxPoints = 30;"
    "if (chartData.labels.length > maxPoints) {"
    "chartData.tempMedia.shift(); chartData.umidade.shift(); chartData.pressao.shift(); chartData.labels.shift();"
    "}"
    "Object.values(charts).forEach(chart => chart.update('none'));"
    "}"
    "function atualizarDados() {"
    "fetch('/dados').then(res => res.json()).then(data => {"
    "atualizarGraficos(data);"
    "});"
    "}"
    "window.onload = function() { criarGraficos(); atualizarDados(); setInterval(atualizarDados, 2000); };"
    "</script></head><body>"
    "<div class='container'>"
    "<h1>📊 Gráficos em Tempo Real</h1>"
    "<div class='nav-buttons'>"
    "<a href='/' class='nav-btn'>🏠 Voltar ao Principal</a>"
    "</div>"
    "<div class='charts-container'>"
    "<div class='charts-grid'>"
    "<div class='chart-card'><div class='chart-title'>Temperatura Média</div><canvas id='chartTempMedia'></canvas></div>"
    "<div class='chart-card'><div class='chart-title'>Umidade</div><canvas id='chartUmidade'></canvas></div>"
    "<div class='chart-card'><div class='chart-title'>Pressão</div><canvas id='chartPressao'></canvas></div>"
    "</div></div>"
    "</div></body></html>";

/* ---- Página de Estados ---------------------------------------- */
const char HTML_ESTADOS[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Estados do Sistema - PicoAtmos</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { font-family: sans-serif; text-align: center; padding: 20px; margin: 0; background: #f0f8ff; }"
    ".container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
    "h1 { color: #2c3e50; margin-top: 0; }"
    ".nav-buttons { margin: 20px 0; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }"
    ".nav-btn { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; text-decoration: none; }"
    ".nav-btn:hover { background: #2980b9; }"
    ".system-status { margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; border: 1px solid #ddd; }"
    ".system-status h3 { color: #2c3e50; margin-top: 0; }"
    ".status-list { display: flex; flex-direction: column; gap: 15px; margin: 20px 0; }"
    ".status-item { padding: 15px; border-radius: 8px; text-align: left; display: flex; justify-content: space-between; align-items: center; }"
    ".status-item.baixo { background: #cce7ff; color: #004085; border-left: 5px solid #007bff; }"
    ".status-item.normal { background: #d4edda; color: #155724; border-left: 5px solid #28a745; }"
    ".status-item.alto { background: #f8d7da; color: #721c24; border-left: 5px solid #dc3545; }"
    ".status-label { font-size: 18px; font-weight: bold; }"
    ".status-value { font-size: 18px; }"
    ".legend-container { margin: 30px 0; padding: 20px; background: #e8f6f3; border-radius: 8px; }"
    ".legend-item { margin: 10px 0; padding: 10px; background: white; border-radius: 5px; display: flex; justify-content: space-between; align-items: center; }"
    ".legend-color { width: 20px; height: 20px; border-radius: 50%; margin-right: 10px; }"
    ".legend-verde { background-color: #28a745; }"
    ".legend-azul { background-color: #007bff; }"
    ".legend-vermelho { background-color: #dc3545; }"
    ".legend-roxo { background-color: #6f42c1; }"
    ".legend-amarelo { background-color: #ffc107; }"
    ".legend-branco { background-color: #6c757d; border: 1px solid #ddd; }"
    "</style>"
    "<script>"
    "function atualizarStatusSistema(data) {"
    "const tempStatus = document.getElementById('temp_status');"
    "const tempValue = tempStatus.querySelector('.status-value');"
    "document.getElementById('temp_atual_value').textContent = data.temp_media.toFixed(1) + '°C';"
    "if (data.temp_media < data.temp_min) {"
    "tempStatus.className = 'status-item baixo';"
    "tempValue.textContent = 'Abaixo do Limite ❄️';"
    "} else if (data.temp_media > data.temp_max) {"
    "tempStatus.className = 'status-item alto';"
    "tempValue.textContent = 'Acima do Limite 🔥';"
    "} else {"
    "tempStatus.className = 'status-item normal';"
    "tempValue.textContent = 'Normal ✅';"
    "}"
    "const umidStatus = document.getElementById('umid_status');"
    "const umidValue = umidStatus.querySelector('.status-value');"
    "document.getElementById('umid_atual_value').textContent = data.umidade.toFixed(1) + '%';"
    "if (data.umidade < data.umid_min) {"
    "umidStatus.className = 'status-item baixo';"
    "umidValue.textContent = 'Abaixo do Limite 🏜️';"
    "} else if (data.umidade > data.umid_max) {"
    "umidStatus.className = 'status-item alto';"
    "umidValue.textContent = 'Acima do Limite 💧';"
    "} else {"
    "umidStatus.className = 'status-item normal';"
    "umidValue.textContent = 'Normal ✅';"
    "}"
    "const pressStatus = document.getElementById('press_status');"
    "const pressValue = pressStatus.querySelector('.status-value');"
    "document.getElementById('press_atual_value').textContent = data.pressao.toFixed(1) + ' hPa';"
    "if (data.pressao < data.press_min) {"
    "pressStatus.className = 'status-item baixo';"
    "pressValue.textContent = 'Abaixo do Limite 🌀';"
    "} else if (data.pressao > data.press_max) {"
    "pressStatus.className = 'status-item alto';"
    "pressValue.textContent = 'Acima do Limite ⬆️';"
    "} else {"
    "pressStatus.className = 'status-item normal';"
    "pressValue.textContent = 'Normal ✅';"
    "}"
    "}"
    "function atualizarDados() {"
    "fetch('/dados').then(res => res.json()).then(data => {"
    "atualizarStatusSistema(data);"
    "});"
    "}"
    "window.onload = function() { atualizarDados(); setInterval(atualizarDados, 2000); };"
    "</script></head><body>"
    "<div class='container'>"
    "<h1>🚨 Estados do Sistema</h1>"
    "<div class='nav-buttons'>"
    "<a href='/' class='nav-btn'>🏠 Voltar ao Principal</a>"
    "</div>"
    "<div class='system-status'>"
    "<h3>Status Atual dos Sensores</h3>"
    "<div class='status-list'>"
    "<div id='temp_status' class='status-item'>"
    "<div><span class='status-label'>Temperatura: </span><span id='temp_atual_value'>--</span></div>"
    "<div><span class='status-value'>--</span></div>"
    "</div>"
    "<div id='umid_status' class='status-item'>"
    "<div><span class='status-label'>Umidade: </span><span id='umid_atual_value'>--</span></div>"
    "<div><span class='status-value'>--</span></div>"
    "</div>"
    "<div id='press_status' class='status-item'>"
    "<div><span class='status-label'>Pressão: </span><span id='press_atual_value'>--</span></div>"
    "<div><span class='status-value'>--</span></div>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='legend-container'>"
    "<h3>Legenda de Cores LED</h3>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-verde'></div>Verde</div><div>Sistema Normal</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-vermelho'></div>Vermelho</div><div>Temperatura Alta</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-azul'></div>Azul</div><div>Temperatura Baixa</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-roxo'></div>Roxo</div><div>Umidade Alta</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-amarelo'></div>Amarelo</div><div>Umidade Baixa</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color legend-branco'></div>Branco</div><div>Pressão Alta</div></div>"
    "<div class='legend-item'><div style='display: flex; align-items: center;'><div class='legend-color' style='background: #495057;'></div>Desligado</div><div>Pressão Baixa</div></div>"
    "</div>"
    "</div></body></html>";

/* ---- Página de Limites ---------------------------------------- */
const char HTML_LIMITES[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Configuração de Limites - PicoAtmos</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { font-family: sans-serif; text-align: center; padding: 20px; margin: 0; background: #f0f8ff; }"
    ".container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
    "h1 { color: #2c3e50; margin-top: 0; }"
    ".nav-buttons { margin: 20px 0; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }"
    ".nav-btn { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; text-decoration: none; }"
    ".nav-btn:hover { background: #2980b9; }"
    ".limits-container { margin: 20px 0; background: #e8f4fd; border-radius: 8px; padding: 20px; }"
    ".limits-help { background: #d1ecf1; padding: 15px; border-radius: 6px; margin-bottom: 20px; text-align: left; font-size: 14px; line-height: 1.4; }"
    ".limits-help h4 { margin-top: 0; color: #2c3e50; }"
    ".limits-section { margin: 15px 0; padding: 15px; background: #ffffff; border-radius: 8px; border: 1px solid #bdc3c7; }"
    ".limits-title { font-weight: bold; margin-bottom: 10px; color: #2c3e50; }"
    ".limits-row { display: flex; justify-content: space-between; align-items: center; margin: 8px 0; flex-wrap: wrap; gap: 10px; }"
    ".limits-inputs { display: flex; gap: 10px; align-items: center; }"
    "input { padding: 8px; border: 1px solid #ddd; border-radius: 4px; width: 100px; }"
    "input:focus { border-color: #27ae60; outline: none; }"
    "button { background: #27ae60; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; }"
    "button:hover { background: #229954; }"
    ".range-display { font-size: 16px; color: #2c3e50; font-weight: bold; }"
    ".success-msg { background: #d4edda; color: #155724; padding: 10px; border-radius: 4px; margin: 10px 0; display: none; }"
    "</style>"
    "<script>"
    "function atualizarLimites() {"
    "const tempMin = document.getElementById('temp_min').value;"
    "const tempMax = document.getElementById('temp_max').value;"
    "const umidMin = document.getElementById('umid_min').value;"
    "const umidMax = document.getElementById('umid_max').value;"
    "const pressMin = document.getElementById('press_min').value;"
    "const pressMax = document.getElementById('press_max').value;"
    "fetch('/set_limits?temp_min=' + tempMin + '&temp_max=' + tempMax + '&umid_min=' + umidMin + '&umid_max=' + umidMax + '&press_min=' + pressMin + '&press_max=' + pressMax)"
    ".then(response => response.text())"
    ".then(data => {"
    "console.log(data);"
    "const msg = document.getElementById('success-msg');"
    "msg.style.display = 'block';"
    "setTimeout(() => { msg.style.display = 'none'; }, 3000);"
    "});"
    "}"
    "function atualizarDados() {"
    "fetch('/dados').then(res => res.json()).then(data => {"
    "document.getElementById('temp_range_display').innerText = data.temp_min.toFixed(1) + ' - ' + data.temp_max.toFixed(1);"
    "document.getElementById('umid_range_display').innerText = data.umid_min.toFixed(1) + ' - ' + data.umid_max.toFixed(1);"
    "document.getElementById('press_range_display').innerText = data.press_min.toFixed(1) + ' - ' + data.press_max.toFixed(1);"
    "document.getElementById('temp_min').value = data.temp_min.toFixed(1);"
    "document.getElementById('temp_max').value = data.temp_max.toFixed(1);"
    "document.getElementById('umid_min').value = data.umid_min.toFixed(1);"
    "document.getElementById('umid_max').value = data.umid_max.toFixed(1);"
    "document.getElementById('press_min').value = data.press_min.toFixed(1);"
    "document.getElementById('press_max').value = data.press_max.toFixed(1);"
    "});"
    "}"
    "window.onload = function() { atualizarDados(); setInterval(atualizarDados, 3000); };"
    "</script></head><body>"
    "<div class='container'>"
    "<h1>⚙️ Configuração de Limites</h1>"
    "<div class='nav-buttons'>"
    "<a href='/' class='nav-btn'>🏠 Voltar ao Principal</a>"
    "</div>"
    "<div id='success-msg' class='success-msg'>Limites atualizados com sucesso!</div>"
    "<div class='limits-container'>"
    "<h3>Configuração de Limites de Alerta</h3>"
    "<div class='limits-help'>"
    "<h4>Como configurar os limites:</h4>"
    "<p>Os limites definem quando os alertas visuais e sonoros serão ativados. Configure os valores mínimo e máximo para cada parâmetro.</p>"
    "<p><strong>🔔 Alertas:</strong> LEDs RGB, buzzer e matriz de LED são ativados quando os valores saem da faixa configurada.</p>"
    "<p><strong>🎯 Dica:</strong> Configure limites adequados para seu ambiente para evitar alarmes desnecessários.</p>"
    "</div>"
    "<div class='limits-section'>"
    "<div class='limits-title'>Temperatura</div>"
    "<div class='limits-row'>"
    "<span>Faixa Atual: <span id='temp_range_display' class='range-display'>--</span>°C</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='temp_min' step='0.1' placeholder='Mínimo'>"
    "<span>até</span>"
    "<input type='number' id='temp_max' step='0.1' placeholder='Máximo'>"
    "<span>°C</span>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='limits-section'>"
    "<div class='limits-title'>Umidade</div>"
    "<div class='limits-row'>"
    "<span>Faixa Atual: <span id='umid_range_display' class='range-display'>--</span>%</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='umid_min' step='1' placeholder='Mínimo'>"
    "<span>até</span>"
    "<input type='number' id='umid_max' step='1' placeholder='Máximo'>"
    "<span>%</span>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='limits-section'>"
    "<div class='limits-title'>Pressão</div>"
    "<div class='limits-row'>"
    "<span>Faixa Atual: <span id='press_range_display' class='range-display'>--</span> hPa</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='press_min' step='0.1' placeholder='Mínimo'>"
    "<span>até</span>"
    "<input type='number' id='press_max' step='0.1' placeholder='Máximo'>"
    "<span>hPa</span>"
    "</div>"
    "</div>"
    "</div>"
    "<button onclick='atualizarLimites()'>💾 Salvar Limites</button>"
    "</div>"
    "</div></body></html>";

/* ---- Página de Calibração ------------------------------------ */
const char HTML_CALIBRACAO[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Calibração - PicoAtmos</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { font-family: sans-serif; text-align: center; padding: 20px; margin: 0; background: #f0f8ff; }"
    ".container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
    "h1 { color: #2c3e50; margin-top: 0; }"
    ".nav-buttons { margin: 20px 0; display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }"
    ".nav-btn { background: #3498db; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; text-decoration: none; }"
    ".nav-btn:hover { background: #2980b9; }"
    ".calibration-container { margin: 20px 0; background: #e8f6f3; border-radius: 8px; padding: 20px; }"
    ".calibration-help { background: #d5f4e6; padding: 15px; border-radius: 6px; margin-bottom: 20px; text-align: left; font-size: 14px; line-height: 1.4; }"
    ".calibration-help h4 { margin-top: 0; color: #2c3e50; }"
    ".calibration-section { margin: 15px 0; padding: 15px; background: #ffffff; border-radius: 8px; border: 1px solid #bdc3c7; }"
    ".limits-title { font-weight: bold; margin-bottom: 10px; color: #2c3e50; }"
    ".limits-row { display: flex; justify-content: space-between; align-items: center; margin: 8px 0; flex-wrap: wrap; gap: 10px; }"
    ".limits-inputs { display: flex; gap: 10px; align-items: center; }"
    "input { padding: 8px; border: 1px solid #ddd; border-radius: 4px; width: 100px; }"
    "input:focus { border-color: #e67e22; outline: none; }"
    "button { background: #e67e22; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; }"
    "button:hover { background: #d35400; }"
    ".current-values { margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 8px; }"
    ".sensor-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 15px 0; }"
    ".sensor-card { background: #ffffff; padding: 15px; border-radius: 8px; border: 1px solid #ddd; }"
    ".sensor-value { font-size: 18px; font-weight: bold; color: #2c3e50; }"
    ".success-msg { background: #d4edda; color: #155724; padding: 10px; border-radius: 4px; margin: 10px 0; display: none; }"
    "</style>"
    "<script>"
    "let ultimaAtualizacao = 0;"
    "let offsetsCarregados = false;"
    "function atualizarCalibracoes() {"
    "const offsetTempAht = document.getElementById('offset_temp_aht').value;"
    "const offsetTempBmp = document.getElementById('offset_temp_bmp').value;"
    "const offsetUmid = document.getElementById('offset_umid').value;"
    "const offsetPress = document.getElementById('offset_press').value;"
    "fetch('/set_offsets?offset_temp_aht=' + offsetTempAht + '&offset_temp_bmp=' + offsetTempBmp + '&offset_umid=' + offsetUmid + '&offset_press=' + offsetPress)"
    ".then(response => response.text())"
    ".then(data => {"
    "console.log(data);"
    "const msg = document.getElementById('success-msg');"
    "msg.style.display = 'block';"
    "setTimeout(() => { msg.style.display = 'none'; }, 3000);"
    "});"
    "}"
    "function inputEstaFocado() {"
    "const activeElement = document.activeElement;"
    "return activeElement && activeElement.tagName === 'INPUT';"
    "}"
    "function atualizarDados() {"
    "if (inputEstaFocado()) {"
    "return;"
    "}"
    "fetch('/dados').then(res => res.json()).then(data => {"
    "document.getElementById('temp_aht_atual').innerText = data.temp_aht.toFixed(2);"
    "document.getElementById('temp_bmp_atual').innerText = data.temp_bmp.toFixed(2);"
    "document.getElementById('umid_atual').innerText = data.umidade.toFixed(2);"
    "document.getElementById('press_atual').innerText = data.pressao.toFixed(2);"
    "if (!offsetsCarregados) {"
    "document.getElementById('offset_temp_aht').value = data.offset_temp_aht.toFixed(2);"
    "document.getElementById('offset_temp_bmp').value = data.offset_temp_bmp.toFixed(2);"
    "document.getElementById('offset_umid').value = data.offset_umid.toFixed(2);"
    "document.getElementById('offset_press').value = data.offset_press.toFixed(2);"
    "offsetsCarregados = true;"
    "}"
    "});"
    "}"
    "window.onload = function() { atualizarDados(); setInterval(atualizarDados, 3000); };"
    "</script></head><body>"
    "<div class='container'>"
    "<h1>🔧 Calibração dos Sensores</h1>"
    "<div class='nav-buttons'>"
    "<a href='/' class='nav-btn'>🏠 Voltar ao Principal</a>"
    "</div>"
    "<div id='success-msg' class='success-msg'>Calibrações salvas com sucesso!</div>"
    "<div class='current-values'>"
    "<h3>Valores Atuais dos Sensores (Já Calibrados)</h3>"
    "<div class='sensor-grid'>"
    "<div class='sensor-card'><div>Temperatura AHT20</div><div class='sensor-value'><span id='temp_aht_atual'>--</span>°C</div></div>"
    "<div class='sensor-card'><div>Temperatura BMP280</div><div class='sensor-value'><span id='temp_bmp_atual'>--</span>°C</div></div>"
    "<div class='sensor-card'><div>Umidade</div><div class='sensor-value'><span id='umid_atual'>--</span>%</div></div>"
    "<div class='sensor-card'><div>Pressão</div><div class='sensor-value'><span id='press_atual'>--</span> hPa</div></div>"
    "</div>"
    "</div>"
    "<div class='calibration-container'>"
    "<h3>Ajustes de Calibração (Offset)</h3>"
    "<div class='calibration-help'>"
    "<h4>Como usar a calibração:</h4>"
    "<p>Use os campos abaixo para compensar variações dos sensores. Compare a leitura atual com um medidor de referência confiável e insira a diferença para corrigir.</p>"
    "<p><strong>Exemplo 1 (Offset Positivo):</strong> Se o sensor marca 24.5°C e o valor real é 25.0°C, insira <strong>+0.5</strong></p>"
    "<p><strong>Exemplo 2 (Offset Negativo):</strong> Se o sensor marca 26.2°C e o valor real é 26.0°C, insira <strong>-0.2</strong></p>"
    "<p><strong>Importante:</strong> A calibração se aplica a todas as telas, gráficos e alertas do sistema.</p>"
    "<p><strong>Dica:</strong> Os valores mostrados acima já incluem a calibração atual. Para calibrar corretamente, zere os offsets, compare com um medidor confiável, e insira a diferença.</p>"
    "</div>"
    "<div class='calibration-section'>"
    "<div class='limits-title'>Temperatura AHT20</div>"
    "<div class='limits-row'>"
    "<span>Offset de Calibração:</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='offset_temp_aht' step='0.01' placeholder='±0.00'>"
    "<span>°C</span>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='calibration-section'>"
    "<div class='limits-title'>Temperatura BMP280</div>"
    "<div class='limits-row'>"
    "<span>Offset de Calibração:</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='offset_temp_bmp' step='0.01' placeholder='±0.00'>"
    "<span>°C</span>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='calibration-section'>"
    "<div class='limits-title'>Umidade</div>"
    "<div class='limits-row'>"
    "<span>Offset de Calibração:</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='offset_umid' step='0.01' placeholder='±0.00'>"
    "<span>%</span>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='calibration-section'>"
    "<div class='limits-title'>Pressão</div>"
    "<div class='limits-row'>"
    "<span>Offset de Calibração:</span>"
    "<div class='limits-inputs'>"
    "<input type='number' id='offset_press' step='0.01' placeholder='±0.00'>"
    "<span>hPa</span>"
    "</div>"
    "</div>"
    "</div>"
    "<button onclick='atualizarCalibracoes()'>🔧 Salvar Calibrações</button>"
    "</div>"
    "</div></body></html>";
